# Generated by Django 5.2.17 on 2026-09-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='voting_access',
            field=models.CharField(choices=[('public', 'Public visitors'), ('authenticated', 'Authenticated users'), ('participants', 'Event participants')], default='participants', max_length=20),
        ),
    ]
