# Generated by Django 5.2.17 on 2026-09-26 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('judging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rubric',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_rubric_name_per_event'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.UniqueConstraint(fields=('rubric', 'name'), name='unique_criterion_name_per_rubric'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='criterion_weight_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='criterion_max_score_is_positive'),
        ),
        migrations.AddField(
            model_name='judgetrack',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_tracks', to='events.event'),
        ),
        migrations.AddField(
            model_name='judgetrack',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_track_scopes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgetrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_scopes', to='events.track'),
        ),
        migrations.AddConstraint(
            model_name='judgetrack',
            constraint=models.UniqueConstraint(fields=('event', 'judge', 'track'), name='unique_judge_track_scope'),
        ),
    ]
