# Generated by Django 5.2.17 on 2026-09-27 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_voting_access'),
        ('judging', '0002_judgetrack_rubric_unique_rubric_name_per_event_and_more'),
        ('submissions', '0002_submission_fixture_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PairwiseComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_comparisons', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_comparisons', to=settings.AUTH_USER_MODEL)),
                ('submission_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_as_a', to='submissions.submission')),
                ('submission_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_as_b', to='submissions.submission')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairwise_wins', to='submissions.submission')),
            ],
            options={
                'ordering': ['submission_a_id', 'submission_b_id', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('judge', 'submission_a', 'submission_b'), name='unique_pairwise_comparison_per_judge_pair'), models.CheckConstraint(condition=models.Q(('submission_a__lt', models.F('submission_b'))), name='pairwise_submissions_are_canonical_and_distinct'), models.CheckConstraint(condition=models.Q(('winner__isnull', True), ('winner', models.F('submission_a')), ('winner', models.F('submission_b')), _connector='OR'), name='pairwise_winner_belongs_to_pair')],
            },
        ),
    ]
