# Generated by Django 5.2.17 on 2026-09-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_fixture_id_and_more'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('submission', 'voter_ref'), name='unique_vote_per_submission_voter_ref'),
        ),
    ]
