"""Server-enforced community voting and gallery comment APIs."""
import hashlib
import secrets

from django.conf import settings
from django.core import signing
from django.core.cache import cache
from django.db import IntegrityError, transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.utils import timezone
from rest_framework import status
from rest_framework.authentication import SessionAuthentication, TokenAuthentication
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from drf_spectacular.utils import OpenApiParameter, OpenApiTypes, extend_schema

from apps.accounts.models import EventMembership
from apps.core.models import AuditLog
from apps.events.models import Event
from apps.judging.services import is_organizer
from apps.submissions.models import Submission
from .models import Comment, Vote


ANONYMOUS_BALLOT_COOKIE = "dogfood_ballot_ref"
ANONYMOUS_BALLOT_SALT = "dogfood.voting.ballot.v1"
AUTHENTICATION = [TokenAuthentication, SessionAuthentication]


def _event_from_request(request, *, data=False):
    source = request.data if data else request.query_params
    slug = source.get("event")
    if slug:
        return Event.objects.filter(slug=slug).first()
    return Event.objects.order_by("pk").first()


def _is_public_submission(submission):
    return submission.status == Submission.Status.SUBMITTED and submission.event.is_published


def _voting_is_open(event):
    now = timezone.now()
    return bool(
        event.voting_start
        and event.voting_end
        and event.voting_start <= now < event.voting_end
    )


def _voting_has_ended(event):
    return bool(event.voting_end and timezone.now() >= event.voting_end)


def _has_voting_access(user, event):
    if event.voting_access == Event.VotingAccess.PUBLIC:
        return True
    if not user.is_authenticated:
        return False
    if event.voting_access == Event.VotingAccess.AUTHENTICATED:
        return True
    return EventMembership.objects.filter(
        user=user,
        event=event,
        role=EventMembership.Role.PARTICIPANT,
        status=EventMembership.Status.ACTIVE,
    ).exists()


def _anonymous_voter_ref(request):
    """Return an opaque, signed browser ballot identity and cookie if renewed.

    `Vote.voter_ref` is `user:<primary-key>` for a logged-in voter and
    `anon:<signed-random-id>` for an anonymous ballot browser. The raw random
    ID is generated by the server, signed before storage in the cookie, and is
    never accepted from a request body. This makes duplicate detection stable
    for a browser while keeping the database identity opaque.
    """
    cookie = request.COOKIES.get(ANONYMOUS_BALLOT_COOKIE)
    if cookie:
        try:
            signing.loads(cookie, salt=ANONYMOUS_BALLOT_SALT, max_age=60 * 60 * 24 * 90)
            return f"anon:{cookie}", None
        except signing.BadSignature:
            pass
    cookie = signing.dumps(secrets.token_urlsafe(24), salt=ANONYMOUS_BALLOT_SALT)
    return f"anon:{cookie}", cookie


def _voter_ref(request):
    if request.user.is_authenticated:
        return f"user:{request.user.pk}", None
    return _anonymous_voter_ref(request)


def _apply_ballot_cookie(response, cookie):
    if cookie:
        response.set_cookie(
            ANONYMOUS_BALLOT_COOKIE,
            cookie,
            max_age=60 * 60 * 24 * 90,
            httponly=True,
            secure=not settings.DEBUG,
            samesite="Lax",
        )
    return response


def _rate_limit_allows(event, voter_ref):
    attempts = getattr(settings, "VOTE_RATE_LIMIT_ATTEMPTS", 5)
    window = getattr(settings, "VOTE_RATE_LIMIT_WINDOW_SECONDS", 60)
    digest = hashlib.sha256(f"{event.pk}:{voter_ref}".encode()).hexdigest()
    key = f"dogfood:vote-rate:{digest}"
    current = cache.get(key)
    if current is None:
        cache.add(key, 1, timeout=window)
        return True
    if current >= attempts:
        return False
    try:
        cache.incr(key)
    except ValueError:
        cache.set(key, current + 1, timeout=window)
    return True


def _ballot_submissions(event, voter_ref):
    """Use a stable pseudorandom ordering for each unique ballot identity."""
    submissions = list(
        Submission.objects.filter(event=event, status=Submission.Status.SUBMITTED)
        .select_related("team", "track")
        .order_by("pk")
    )
    return sorted(
        submissions,
        key=lambda submission: hashlib.sha256(
            f"{voter_ref}:{submission.pk}".encode()
        ).digest(),
    )


def _vote_preconditions(request, event):
    if not event or not event.is_published:
        return Response({"error": "Event not found."}, status=status.HTTP_404_NOT_FOUND)
    if not _voting_is_open(event):
        return Response({"error": "Voting is not currently open."}, status=status.HTTP_403_FORBIDDEN)
    if not _has_voting_access(request.user, event):
        return Response({"error": "This event's voting access policy does not permit you to vote."}, status=status.HTTP_403_FORBIDDEN)
    return None


@extend_schema(
    tags=["Voting"],
    summary="Get a randomized community ballot",
    description=(
        "Available only for a published event with an open voting window and the "
        "event's configured public, authenticated, or participant access policy. "
        "A browser ballot identity determines the stable randomized project order."
    ),
    parameters=[OpenApiParameter("event", OpenApiTypes.STR, OpenApiParameter.QUERY, required=False)],
    responses={200: OpenApiTypes.OBJECT, 403: OpenApiTypes.OBJECT, 404: OpenApiTypes.OBJECT},
)
@api_view(["GET"])
@authentication_classes(AUTHENTICATION)
@permission_classes([AllowAny])
def ballot(request):
    """Return the caller's randomized submitted-project ballot."""
    event = _event_from_request(request)
    denied = _vote_preconditions(request, event)
    if denied:
        return denied
    voter_ref, cookie = _voter_ref(request)
    response = Response({
        "event": event.slug,
        "projects": [
            {
                "id": submission.pk,
                "fixture_id": submission.fixture_id,
                "title": submission.title,
                "summary": submission.summary,
                "track": submission.track.name if submission.track else None,
            }
            for submission in _ballot_submissions(event, voter_ref)
        ],
    })
    return _apply_ballot_cookie(response, cookie)


@extend_schema(
    tags=["Voting"],
    summary="Cast a community vote",
    description=(
        "Requires the same active ballot conditions as the ballot endpoint. Only "
        "submitted projects are eligible. Duplicate votes are blocked by a database "
        "constraint and repeated attempts are rate limited."
    ),
    request=OpenApiTypes.OBJECT,
    responses={201: OpenApiTypes.OBJECT, 403: OpenApiTypes.OBJECT, 404: OpenApiTypes.OBJECT, 409: OpenApiTypes.OBJECT, 429: OpenApiTypes.OBJECT},
)
@api_view(["POST"])
@authentication_classes(AUTHENTICATION)
@permission_classes([AllowAny])
def cast_vote(request):
    event = _event_from_request(request, data=True)
    denied = _vote_preconditions(request, event)
    if denied:
        return denied
    submission = Submission.objects.select_related("event").filter(
        pk=request.data.get("submission_id"),
        event=event,
        status=Submission.Status.SUBMITTED,
    ).first()
    if not submission:
        return Response({"error": "Submitted project not found."}, status=status.HTTP_404_NOT_FOUND)

    voter_ref, cookie = _voter_ref(request)
    if not _rate_limit_allows(event, voter_ref):
        return _apply_ballot_cookie(Response(
            {"error": "Too many vote attempts. Please wait before trying again."},
            status=status.HTTP_429_TOO_MANY_REQUESTS,
        ), cookie)
    try:
        with transaction.atomic():
            vote = Vote(submission=submission, voter_ref=voter_ref)
            # Keep model validation for eligibility, but let the database
            # constraint be the authoritative duplicate-vote guard.
            vote.full_clean(validate_constraints=False)
            vote.save()
            AuditLog.objects.create(
                actor=request.user if request.user.is_authenticated else None,
                action="vote.created",
                target_type="Vote",
                target_id=str(vote.pk),
                metadata={
                    "event": event.slug,
                    "submission_id": submission.pk,
                    "voter_ref": voter_ref,
                },
            )
    except IntegrityError:
        return _apply_ballot_cookie(Response(
            {"error": "You have already voted for this project."},
            status=status.HTTP_409_CONFLICT,
        ), cookie)
    return _apply_ballot_cookie(Response(
        {"id": vote.pk, "submission_id": submission.pk, "status": "recorded"},
        status=status.HTTP_201_CREATED,
    ), cookie)


@extend_schema(
    tags=["Voting"],
    summary="Read community voting results",
    description=(
        "Organizer/admin callers may inspect results during voting. Other callers can "
        "read results only after the configured voting window ends."
    ),
    parameters=[OpenApiParameter("event", OpenApiTypes.STR, OpenApiParameter.QUERY, required=False)],
    responses={200: OpenApiTypes.OBJECT, 403: OpenApiTypes.OBJECT, 404: OpenApiTypes.OBJECT},
)
@api_view(["GET"])
@authentication_classes(AUTHENTICATION)
@permission_classes([AllowAny])
def voting_results(request):
    event = _event_from_request(request)
    if not event or not event.is_published:
        return Response({"error": "Event not found."}, status=status.HTTP_404_NOT_FOUND)
    organizer = request.user.is_authenticated and is_organizer(request.user, event)
    if not organizer and not _voting_has_ended(event):
        return Response({"error": "Voting results are hidden until voting ends."}, status=status.HTTP_403_FORBIDDEN)
    results = (
        Submission.objects.filter(event=event, status=Submission.Status.SUBMITTED)
        .annotate(vote_count=Count("votes"))
        .order_by("-vote_count", "pk")
    )
    return Response({
        "event": event.slug,
        "results": [
            {"submission_id": result.pk, "title": result.title, "vote_count": result.vote_count}
            for result in results
        ],
    })


def _public_submission_or_404(submission_id):
    return get_object_or_404(
        Submission.objects.select_related("event"),
        pk=submission_id,
        status=Submission.Status.SUBMITTED,
        event__is_published=True,
    )


def _can_comment(user, submission):
    return user.is_authenticated and EventMembership.objects.filter(
        user=user,
        event=submission.event,
        status=EventMembership.Status.ACTIVE,
    ).exists()


def _comment_body(data):
    body = data.get("body", "")
    return body.strip() if isinstance(body, str) else None


@extend_schema(
    methods=["GET"],
    tags=["Comments"],
    summary="List visible project comments",
    description=(
        "Public readers receive only visible comments on submitted projects in "
        "published events. Organizer/admin callers may add `include_hidden=1` to "
        "inspect hidden comments."
    ),
    parameters=[OpenApiParameter("include_hidden", OpenApiTypes.BOOL, OpenApiParameter.QUERY, required=False)],
    responses={200: OpenApiTypes.OBJECT, 404: OpenApiTypes.OBJECT},
)
@extend_schema(
    methods=["POST"],
    tags=["Comments"],
    summary="Create a project comment",
    description="Requires TokenAuthentication and active membership in the submission's event.",
    request=OpenApiTypes.OBJECT,
    responses={201: OpenApiTypes.OBJECT, 400: OpenApiTypes.OBJECT, 401: OpenApiTypes.OBJECT, 403: OpenApiTypes.OBJECT, 404: OpenApiTypes.OBJECT},
)
@api_view(["GET", "POST"])
@authentication_classes(AUTHENTICATION)
@permission_classes([AllowAny])
def comments(request, submission_id):
    submission = _public_submission_or_404(submission_id)
    if request.method == "GET":
        include_hidden = (
            request.query_params.get("include_hidden") == "1"
            and request.user.is_authenticated
            and is_organizer(request.user, submission.event)
        )
        queryset = submission.comments.select_related("user")
        if not include_hidden:
            queryset = queryset.filter(is_hidden=False)
        return Response({
            "submission_id": submission.pk,
            "comments": [
                {
                    "id": comment.pk,
                    "author": comment.user.username,
                    "body": comment.body,
                    "created_at": comment.created_at,
                    "is_hidden": comment.is_hidden,
                }
                for comment in queryset
            ],
        })
    if not request.user.is_authenticated:
        return Response({"error": "Authentication is required to comment."}, status=status.HTTP_401_UNAUTHORIZED)
    if not _can_comment(request.user, submission):
        return Response({"error": "You do not have permission to comment on this event."}, status=status.HTTP_403_FORBIDDEN)
    body = _comment_body(request.data)
    if body is None:
        return Response({"body": ["Comment body must be text."]}, status=status.HTTP_400_BAD_REQUEST)
    comment = Comment(submission=submission, user=request.user, body=body)
    try:
        comment.full_clean()
    except Exception as exc:
        return Response(getattr(exc, "message_dict", {"error": str(exc)}), status=status.HTTP_400_BAD_REQUEST)
    comment.save()
    AuditLog.objects.create(
        actor=request.user,
        action="comment.created",
        target_type="Comment",
        target_id=str(comment.pk),
        metadata={"submission_id": submission.pk},
    )
    return Response(
        {"id": comment.pk, "submission_id": submission.pk, "body": comment.body},
        status=status.HTTP_201_CREATED,
    )


@extend_schema(
    tags=["Comments"],
    summary="Edit a comment",
    description="Requires TokenAuthentication. Only the comment's author may edit its body.",
    request=OpenApiTypes.OBJECT,
    responses={200: OpenApiTypes.OBJECT, 400: OpenApiTypes.OBJECT, 401: OpenApiTypes.OBJECT, 403: OpenApiTypes.OBJECT, 404: OpenApiTypes.OBJECT},
)
@api_view(["PATCH"])
@authentication_classes(AUTHENTICATION)
@permission_classes([AllowAny])
def edit_comment(request, comment_id):
    comment = get_object_or_404(Comment.objects.select_related("submission__event"), pk=comment_id)
    if not request.user.is_authenticated:
        return Response({"error": "Authentication is required."}, status=status.HTTP_401_UNAUTHORIZED)
    if comment.user_id != request.user.id:
        return Response({"error": "You can only edit your own comments."}, status=status.HTTP_403_FORBIDDEN)
    body = _comment_body(request.data)
    if body is None:
        return Response({"body": ["Comment body must be text."]}, status=status.HTTP_400_BAD_REQUEST)
    comment.body = body
    try:
        comment.full_clean()
    except Exception as exc:
        return Response(getattr(exc, "message_dict", {"error": str(exc)}), status=status.HTTP_400_BAD_REQUEST)
    comment.save(update_fields=["body"])
    AuditLog.objects.create(
        actor=request.user,
        action="comment.updated",
        target_type="Comment",
        target_id=str(comment.pk),
        metadata={"submission_id": comment.submission_id},
    )
    return Response({"id": comment.pk, "body": comment.body})


@extend_schema(
    tags=["Comments"],
    summary="Hide or unhide a comment",
    description="Requires TokenAuthentication and organizer/admin membership in the comment's event.",
    request=OpenApiTypes.OBJECT,
    responses={200: OpenApiTypes.OBJECT, 400: OpenApiTypes.OBJECT, 401: OpenApiTypes.OBJECT, 403: OpenApiTypes.OBJECT, 404: OpenApiTypes.OBJECT},
)
@api_view(["POST"])
@authentication_classes(AUTHENTICATION)
@permission_classes([AllowAny])
def moderate_comment(request, comment_id):
    comment = get_object_or_404(Comment.objects.select_related("submission__event"), pk=comment_id)
    if not request.user.is_authenticated or not is_organizer(request.user, comment.submission.event):
        return Response({"error": "Organizer access is required."}, status=status.HTTP_403_FORBIDDEN)
    is_hidden = request.data.get("is_hidden")
    if not isinstance(is_hidden, bool):
        return Response({"error": "is_hidden must be a boolean."}, status=status.HTTP_400_BAD_REQUEST)
    comment.is_hidden = is_hidden
    comment.save(update_fields=["is_hidden"])
    AuditLog.objects.create(
        actor=request.user,
        action="comment.hidden" if is_hidden else "comment.unhidden",
        target_type="Comment",
        target_id=str(comment.pk),
        metadata={"submission_id": comment.submission_id},
    )
    return Response({"id": comment.pk, "is_hidden": comment.is_hidden})
